### PR TITLE
PHP 8.0 Support

### PR DESCRIPTION
**Pull request by Nielsvanpach**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | no
| New feature?      | yes
| BC breaks?        | no     
| Related Issue     | /
| Need Doc update   | no

## Describe your change

Provide support on PHP 8.0.
I'll keep this PR in Draft until all dependencies can handle PHP 8.0

**Waiting for:**
- [x] migration Travis to Circle CI
- [x] algolia/algoliasearch-client-php (https://github.com/algolia/algoliasearch-client-php/pull/644)
- [x] laravel/scout (https://github.com/laravel/scout/pull/425)

### CODE REVIEW

**Comment by Nielsvanpach** [comment]
Some tests are failing over an API key. Can any of you figure that one out?

```Algolia\AlgoliaSearch\Exceptions\BadRequestException: Invalid Application-ID or API key```

**Comment by DevinCodes** [comment]
Hi @Nielsvanpach, thank you for this PR!

I've tried to rerun the test to see if the error is still there. When I do this, the tests still fail, but I get another error. This leads me to believe your initial errors had something to do with CircleCI permissions, I'll try to make some time to look into that. The new error is this: `Error: Call to undefined method Tests\Features\WhereQueriesTest::getAnnotations()`. You can check the trace in [CircleCI](https://app.circleci.com/pipelines/github/algolia/scout-extended/10/workflows/53e335a8-7c6b-476f-b61d-de90db60f921/jobs/66) to debug.

**Comment by Nielsvanpach** [comment]
I think I solved the getAnnotations() issue, @DevinCodes.
But the initial error still occurs. Could you or someone of the Algolia team look into this? It would really be great to finally have PHP 8 support on the Algolia libraries, as this is the last blocking dependency for a lot of packages and projects.

```
Algolia\AlgoliaSearch\Exceptions\BadRequestException: Invalid Application-ID or API key
```

**Comment by DevinCodes** [comment]
I'll try to take a look at the errors early this week, @Nielsvanpach ! I'll also discuss with the team to see how we can move PHP8 compatibility forward as soon as possible. 

In the meanwhile, thank you for the patience and for your contribution. I'll let you know when I learn more!

**Comment by DevinCodes** [comment]
Just a quick update: I've been trying to fix the error in the CI that keeps showing up, but I think there's an issue with the API key dealer. I'll have to dig deeper into that to get this fixed. Until that time, I'll manually run the test suite so that we're sure the tests pass once the API client supports PHP8.

Regarding PHP8 support, we're discussing internally how we can best tackle this, I hope we can give you an update soon. Thanks again for your patience.

**Comment by Nielsvanpach** [comment]
@DevinCodes last conflicts seem to be fixed. Can you run the tests again?

**Comment by asivaneswaran** [comment]
@DevinCodes @Nielsvanpach 
Any updates on when this is going to go through?

**Comment by Nielsvanpach** [comment]
No updates, we have to wait for Algolia on this one. But let them enjoy their holiday break first :-)

**Comment by lahivee** [comment]
Thanks to Spatie helping out Algolia updating their products

**Comment by DevinCodes** [comment]
Sorry for the delay, I've been vacationing for the last 2 weeks. I'll run the test suite, if all is good I think we're good to go! Thank you so much for your help on this @Nielsvanpach ! 🙇

**Review by DevinCodes — APPROVED** [review]

**Comment by michavie** [comment]
thank you & happy new year!

**Comment by lahivee** [comment]
thanks!

**Comment by lahivee** [comment]
Thank you @DevinCodes , please also release this please

**Comment by DevinCodes** [comment]
@lahivee It's released in `v1.11.0`:
* https://github.com/algolia/scout-extended/releases/tag/v1.11.0
* https://packagist.org/packages/algolia/scout-extended#v1.11.0

**Comment by lahivee** [comment]
@DevinCodes thank you, I appreciate it!

**Pull request merged**
