### PR TITLE
Fix empty searchable array got indexed when soft delete meta data is enabled.

### PR DESCRIPTION
**Pull request by wisoot**
When looping through searchable models, skip any model that return searchable array as empty.

This will solve #192

### CODE REVIEW

**Comment by tom-odonahoo** [comment]
@nunomaduro Just thought I'd drop you a friendly reminder about this one if you get a moment. This issue this PR would solve is causing us to have an unusually large bill in Algolia due to large amounts of soft deleted records being indexed. Thanks again!

**Comment by nunomaduro** [comment]
I am in vacations at the moment, @chloelbn can you double check this ?

**Comment by chloelbn** [comment]
Hello @wisoot and @tom-odonahoo!

First of all sorry for the delay to review your PR.
You've done a great job so far, thanks a lot! But I tried to run your tests without your fix and they're all green, I think they're not testing exactly what you are trying to achieve. You might want to:
- add the `soft_delete` option to true, like in this test https://github.com/algolia/scout-extended/blob/master/tests/Features/AggregatorTest.php#L124
- make sure you are testing an entity that contains soft_deleted entries, to make sure they're skipped

Don't hesitate if you have any questions,

**Comment by wisoot** [comment]
@chloelbn Thanks for the reply.

I've run the test without the fix and this is what I got.

```
phpunit tests/Features/SearchableTest.php
PHPUnit 8.2.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.18 with Xdebug 2.6.0
Configuration: /var/www/phpunit.xml.dist

.E                                                                  2 / 2 (100%)

Time: 3.65 seconds, Memory: 22.00 MB

There was 1 error:

1) Tests\Features\SearchableTest::testSearchableWithEmptySearchableArray
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0_Algolia_AlgoliaSearch_SearchIndex::saveObjects([0 => [...]]). Either the method was unexpected or its arguments matched no expected argument list for this method



/var/www/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:92
/var/www/src/Jobs/UpdateJob.php:137
/var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32
/var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:90
/var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:34
/var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php:576
/var/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:94
/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128
/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
/var/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:98
/var/www/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:413
/var/www/src/Engines/AlgoliaEngine.php:70
/var/www/vendor/laravel/scout/src/Searchable.php:63
/var/www/vendor/laravel/scout/src/Searchable.php:42
/var/www/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:110
/var/www/vendor/laravel/scout/src/Searchable.php:139
/var/www/tests/Features/SearchableTest.php:45

ERRORS!
Tests: 2, Assertions: 0, Errors: 1.
```

When I added the line you mentioned I didn't get any different result.

Could you double check and let me know if I miss anything.

**Comment by wisoot** [comment]
@chloelbn Just dropping a reminder that I'm still waiting for your reply.
I might not be clear in my previous reply but I didn't see all green when running the test with the fix commented out and got the error as shown in above post.

**Comment by nunomaduro** [comment]
@wisoot My colleague entered in vacations, and I am in vacations too.

Next week, we will take a look into this. Thanks for your reminder buddy!

**Comment by chloelbn** [comment]
@nunomaduro @wisoot Indeed I was not precise enough, it is the ImportCommandTest that pass without the fix. I would suggest implementing a factory for EmptyItem like on this line https://github.com/algolia/scout-extended/blob/89f5982837ed2de8a2d80dd00e86c7efd5d82048/tests/Features/ImportCommandTest.php#L24 

Don't hesitate and come back to me if it's unclear

**Comment by wisoot** [comment]
@chloelbn That makes sense. Got what you mean now. I've added the fix as you suggested. Let me know what else do you need?

**Comment by nunomaduro** [comment]
Thanks !

**Pull request merged**
