### PR TITLE
Add support for Laravel 9

### PR DESCRIPTION
**Pull request by Nielsvanpach**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | no
| New feature?      | no    
| BC breaks?        | no     
| Related Issue     |
| Need Doc update   | 

## Describe your change

This PR follows up on https://github.com/algolia/scout-extended/pull/295

- Add support for upcoming release of Laravel 9
- Use the stable release of phpstan

### CODE REVIEW

**Comment by DevinCodes** [comment]
Hey @Nielsvanpach , thank you for starting this PR, and sorry for the delay in handling it.

I've made some changes to get the CI to pass. One of them is lowering the PHPStan level: on the max level, there were too many changes to address before the release of Laravel 9. To make sure Scout Extended is available when it releases, I've lowered the level, and we'll gradually increase it over time to get back to the max level.

**Comment by GC-Mark** [comment]
Any chance of getting `v2.0` released soon?

**Comment by DevinCodes** [comment]
@GC-Mark It's out already 😄  https://packagist.org/packages/algolia/scout-extended#v2.0.1

**Comment by GC-Mark** [comment]
Ah, cool, thanks 👍 

Didn't see it listed here - https://github.com/algolia/scout-extended/releases

**Comment by DevinCodes** [comment]
Good catch, I'll add it there!

**Pull request merged**
