### PR TITLE
Ignore import errors when scannig for searchables

### LINKED ISSUE #213: [Bug] Loading all files in app()->path() will cause errors when dependencies aren't loaded
Consider the following code from this repo: https://github.com/algolia/scout-extended/blob/ea5cec58af8f726fe1f5848082c0a5f84ffbd3b8/src/Helpers/SearchableFinder.php#L97-L101

In practice, this will load all `*.php` files . in your `app/` directory.

We have some service providers (e.g. `app/Providers/TelescopeServiceProvider`) that only load when on local. These classes depend on `laravel/telescope` to be installed via composer. Because these packages are a `--dev` requirement, they won't be installed in production.

However, because this piece of code is trying to load all files, php needs to be able to resolve the dependencies these files depend on. In the case of my `app/Providers/TelescopeServiceProvider`, this fails because `laravel/telescope` isn't installed in production:

```
In TelescopeServiceProvider.php line 10:
                                                                           
  Class 'Laravel\Telescope\TelescopeApplicationServiceProvider' not found  
```

I'm not sure what would be the best way to resolve this. Silence errors? Add a blacklist to ignore certain classes from being loaded?

### PR DESCRIPTION
**Pull request by georgeboot**
Fixes #213 

Re-submit of #214

### CODE REVIEW

**Comment by DevinCodes** [comment]
Thank you for re-opening the PR @georgeboot !

I re-ran the tests with the right credentials, but the tests fail with the following error, would you mind having a look please?

```
There was 1 error:

1) Tests\Features\SearchableFinderTest::testWhenThereIsAnUnresolvableClass
Mockery\Exception\BadMethodCallException: Received Mockery_5_Illuminate_Console_OutputStyle::askQuestion(), but no expectations were specified

/home/circleci/project/vendor/symfony/console/Style/SymfonyStyle.php:288
/home/circleci/project/src/Console/Commands/SyncCommand.php:55
/home/circleci/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
/home/circleci/project/vendor/laravel/framework/src/Illuminate/Container/Util.php:37
/home/circleci/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
/home/circleci/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37
/home/circleci/project/vendor/laravel/framework/src/Illuminate/Container/Container.php:590
/home/circleci/project/vendor/laravel/framework/src/Illuminate/Console/Command.php:134
/home/circleci/project/vendor/symfony/console/Command/Command.php:255
/home/circleci/project/vendor/laravel/framework/src/Illuminate/Console/Command.php:121
/home/circleci/project/vendor/symfony/console/Application.php:1009
/home/circleci/project/vendor/symfony/console/Application.php:273
/home/circleci/project/vendor/symfony/console/Application.php:149
/home/circleci/project/vendor/laravel/framework/src/Illuminate/Console/Application.php:93
/home/circleci/project/vendor/laravel/framework/src/Illuminate/Console/Application.php:185
/home/circleci/project/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:273
/home/circleci/project/vendor/laravel/framework/src/Illuminate/Foundation/Testing/PendingCommand.php:137
/home/circleci/project/vendor/laravel/framework/src/Illuminate/Foundation/Testing/PendingCommand.php:223
/home/circleci/project/tests/Features/SearchableFinderTest.php:20
```

**Comment by georgeboot** [comment]
@DevinCodes I can not replicate that error. How can I run tests locally without real Algolia credentials?

It seems like `SyncCommand` aks some interactive questions regarding on the status of the searchable and the index. The command is mocked and is not expecting this question.

If I can figure out which question it is asking, I can just add that to the mock chain and we should be good to go. Bit of a small, but it'll do.

**Comment by DevinCodes** [comment]
I tried to run the tests locally to see if I can reproduce. The weird thing is that the test passes when I run it in isolation, but it fails when I run the full test suite. There might be something (a mock or something similar) that happens in another test that makes this test fail. 

I'll try to dig a bit deeper today.

**Comment by DevinCodes** [comment]
I found the issue: we only run the logic in `getProjectClasses` once, because we cache the retrieved classes in a static property. This prevents your test from including the non-existing file if the `getProjectClasses` method already ran before.

Could you please refactor this static property (`$declaredClasses`, see line 34 of the `SearchableFinder` class) so that it's not static anymore? This still allows for caching of the classes, albeit on the instance level instead of on the class level. This change should fix the issue and make the tests green. Thank you in advance!

**Comment by georgeboot** [comment]
@DevinCodes done

**Review by DevinCodes — APPROVED** [review]
Thank you for your work on this! I'll release this later today 😄

**Pull request merged**
