### PR TITLE
Fix Aggregator Collection macros being overwritten when other models boot

### LINKED ISSUE #305: Scout's collection macros override Scout Extended's if regular models booted after Aggregator
- Laravel version: 9.8.1
- Algolia Scout Extended version: 2.0.2
- Algolia Client Version: 3.2.0
- Language Version: 8.1.4

### Description

I have a simple aggregator that indexes my `Event` and `Hub` models, and just today I started getting a `ModelNotDefinedInAggregatorException` thrown any time I tried to save a Hub. Digging around in the stack trace I realized that the `queueRemoveFromSearch` method was being called from inside my `Page` model, which is also searchable but not part of an aggregator.

I think what's happening is that Scout's `Searchable` trait, which registers new `searchable` and `unsearchable` methods on the base Illuminate Collection, basically proxies those methods through to corresponding methods **on the particular class that registers the macros**. Because many different models can use the `Searchable` trait and each will boot it independently, this effectively means that the Collection macros will always end up calling `queueMakeSearchable` and `queueRemoveFromSearch` on whichever model booted the `Searchable` trait **last**.

In most apps this wouldn't matter because every model is using the the same `Searchable` trait, so the methods all do the same thing, but Scout Extended's aggregators override the booting of the `Searchable` trait and re-register the macros (along with their own observers). In my app I'm registering my own observers in a couple places, and they get registered after I call `bootSearchable` on my aggregator, and somehow, Scout Extended's macros or observers are being overridden by Scout's own.

If I comment out or move around my own observers so that my aggregator is the last thing to call `bootSearchable`, everything seems to work fine. If I fiddle with the order, the `ModelNotDefined...` exception always reports that it's coming from the model that had its observers registered _last_.

I think this started when I upgraded to v2, but I can't be sure. The only PR I can find recently that could have tweaked this behaviour is #239, but I can't figure out how it could be causing this.

### Steps To Reproduce

Register any model observer on a regular searchable model _after_ calling `bootSearchable` on an aggregator, then save one of the aggregator's models and see the above error.

I will spin up a new app and work on putting together a minimal reproduction of this.

### PR DESCRIPTION
**Pull request by bakerkretzmar**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Related Issue     | Fix #305
| Need Doc update   | no

## Describe your change

This PR adds an `unsearchable` method to Scout Extended's `AggregatorCollection` class. This ensures that any time an Aggregator is removed from search, it gets removed using the `queueRemoveFromSearch` method on itself or on the base `Aggregator` class it extends, _never_ the method in Scout's base `Searchable` trait.

The issue is demonstrated with a failing test in the first commit, the fix is included in the second commit and that test should then pass.

I also removed the manual re-registration of the Collection macros in the aggregator, since it's now unnecessary—for `searchable`, Scout Extended's behaviour is the same as Scout's, and for `unsearchable`, Scout Extended now doesn't use a macro at all.

## What problem is this fixing?

Any time any Searchable Eloquent model boots, it registers Scout's base `searchable` and `unsearchable` Collection macros. Scout Extended's Aggregators also register these same macros, overriding Scout's, specifically to avoid queuing the removal of deleted models. If any Searchable model boots _after_ an Aggregator`, Scout's macros will be re-registered, overriding Scout Extended's. Fixes #305.

cc @DevinCodes

### CODE REVIEW

**Review by DevinCodes — APPROVED** [review]
Thank you for the PR @bakerkretzmar , this looks good to me. We'll try to release this, this week 🙂

**Comment by bakerkretzmar** [comment]
Awesome, thanks!

**Comment by JayBizzle** [comment]
We have just updated our application the the latest version of this package (v2.0.2 -> v2.0.3) which includes this PR and it is causing all indexing operations to fail for us.

We get the follow exception whenever an indexing operation is performed...

```
BadMethodCallException: Method Illuminate\Database\Eloquent\Collection::searchable does not exist.
```

Surely this stems from the removal of this line?

https://github.com/algolia/scout-extended/blob/1534b7060f70f82ceade6b50db2e8a9ac8b5869f/src/Searchable/Aggregator.php#L65

**Comment by JayBizzle** [comment]
On further investigation, it seems that this stems from the fact that we don't use the `Searchable` trait on our models, as we don't want to create individual Model indexes. We only want the aggregated index.

**Comment by bakerkretzmar** [comment]
Interesting. Now that Scout Extended is not using the macros at all it probably doesn't make any difference to add that back. Thanks for the ping, looks like @DevinCodes is about to PR a fix but let me know if you need anything else 👍🏻 sorry about that!

**Comment by JayBizzle** [comment]
No worries. I guess we are all using this in various different ways and it is sometime tricky to think of everyone else's use cases.

PR #310 fixes the issue for us 👍 

Fingers crossed for a fast merge. Maybe some tests would be good around this issue.

**Comment by DevinCodes** [comment]
@JayBizzle Do you have a short snippet we could use to reproduce this, please?

I'll make sure to merge and release this today so we can fix this asap, but I'd like to add a test if possible to prevent this from occurring again.

**Comment by JayBizzle** [comment]
I'll try and put together example this evening, but basically it would involve creating an `Aggregator`, of which the `Models` defined _do not_ use the use the `Searchable` trait.

**Comment by DevinCodes** [comment]
Thanks, I've been able to reproduce it indeed, #310 will resolve the issue. I'll merge and release, and take time to write tests for this later in the week to prevent this from creeping in again.

Thank you both for your help on this!

**Pull request merged**
