### PR TITLE
[BUG] - empty whereIn array results in condition ignored

### LINKED ISSUE #200: [bug] Passing an empty array to ->whereIn() ignores the whole statement
If you pass an empty array as the second argument in a `->whereIn()` the whole statement appears to be ignored.

```
App\Model::search($query)->whereIn('author_id', [])->get()
```

I would expect that to return no results, since there's nothing being passed in. However, in practice it ignores it completely and returns the same results as `App\Model::search($query)->get()`

### PR DESCRIPTION
**Pull request by VinceG**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | Yes
| New feature?      | No
| BC breaks?        | no     
| Related Issue     | Fix #200 
| Need Doc update   | no

## Describe your change

This will add an empty condition to the whereIn method to make sure it'll add the condition only if the array is not empty. if it's empty it'll add a false condition to make sure the condition will stop ALL records from being returned.

## What problem is this fixing?

Originally passing an empty array to `whereIn` resulted in ignoring the entire condition, this results in unexpected search results where a user might see more results than they should.

For example

```
// Returns all records matching the query ignores the id condition
// it'll return all results matching the search query and ignores completely the whereIn condition
$query = App\Models\Areas\Area::search('santa')->whereIn('author_id', [])->get();
```

With this fix, it'll do exactly what Laravel does with its query builder where if the array is empty it'll append a false condition.

```
// Returns all records matching the query appends 0 = 1 similar to how laravel handles the whereIn with empty array
// https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Query/Grammars/Grammar.php#L271
$query = App\Models\Areas\Area::search('santa')->whereIn('id', [])->get();
```

added a corresponding test to make sure everything passes with this change.

### CODE REVIEW

**Comment by VinceG** [comment]
Looks like the tests are failing but not related to this PR.

**Comment by DevinCodes** [comment]
I re-ran the tests so that the credentials work properly (sorry for the inconvenience on that).

It seems like there are some PHPStan errors that make the CI fail, but this is unexpected. There's an [issue on the PHPStan repo](https://github.com/phpstan/phpstan/issues/4579) that describes the same situation we're encountering. We have to wait until [this commit](https://github.com/phpstan/phpstan-src/commit/70756b0939512ff0408299607b4d073f599df244) is released, or ignore the errors for now through the `phpstan.neon.dist` file.

**Comment by DevinCodes** [comment]
@VinceG Let's unblock this, and ignore the PHPStan errors for now. I'll make sure keep track of this in the coming days/weeks.

Can you please ignore the errors for now by adding the following to the `phpstan.neon.dist` file, under the `ignoreErrors` key? Thank you in advance!

```
- '#Cannot call method withScoutMetadata\(\) on class-string\|object.#'
- '#Cannot call method getScoutKey\(\) on class-string\|object.#'
- '#Cannot call method toSearchableArray\(\) on class-string\|object.#'
```

**Comment by VinceG** [comment]
@DevinCodes Done.

**Review by DevinCodes — APPROVED** [review]
Thank you for the PR @VinceG ! I'll merge and release this soon 🚀

**Comment by DevinCodes** [comment]
This fix is released in [`v1.14.0`](https://github.com/algolia/scout-extended/releases/tag/v1.14.0) 🎉 

Thank you again for your contribution!

**Pull request merged**
